server:
  port: 9000

spring:
  application:
    name: flowable-demo

  datasource:
    url: jdbc:mysql://localhost:3306/flowable?serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true